"use client";

import { useState } from "react";
import { FileText, Loader2, ShieldCheck } from "lucide-react";
import { GlassCard } from "@/components/ui/GlassCard";
import { Button } from "@/components/ui/Button";
import { useFunnel } from "@/lib/store";

/**
 * Paid deep-dive report, generated by Claude Vision — the real API call
 * happens here, AFTER payment (cost optimization), and only with the
 * user's explicit consent to transmit the two photos once.
 */
export function FullReport() {
  const { photos, quiz, metrics } = useFunnel();
  const [consent, setConsent] = useState(false);
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  if (!metrics) return null;

  const generate = async () => {
    if (!photos.front) {
      setError(
        "Your photos are no longer in this browser session (they are never stored). Run a new scan to generate the report.",
      );
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          front: photos.front.dataUrl,
          side: photos.side?.dataUrl ?? null,
          quiz,
          metrics,
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error ?? `Report generation failed (${res.status}).`);
      } else {
        setReport(data.report);
      }
    } catch {
      setError("Network error — please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <GlassCard className="p-8">
      <div className="flex items-center gap-2 text-sm font-medium text-zinc-200">
        <FileText className="h-4 w-4 text-accent" /> AI Deep-Dive Report
      </div>

      {report ? (
        <div className="prose-invert mt-6 whitespace-pre-wrap text-sm leading-relaxed text-zinc-300">
          {report}
        </div>
      ) : (
        <>
          <p className="mt-2 text-sm text-zinc-400">
            Your full report is generated by Claude Vision from your two
            photos, your scan measurements and your quiz answers.
          </p>
          <label className="mt-5 flex cursor-pointer items-start gap-3 rounded-2xl border border-white/10 bg-white/[0.02] p-4">
            <input
              type="checkbox"
              checked={consent}
              onChange={(e) => setConsent(e.target.checked)}
              className="mt-0.5 h-4 w-4 accent-[#95BF47]"
            />
            <span className="text-xs leading-relaxed text-zinc-400">
              I agree that my two photos are transmitted once, securely, for
              AI processing to generate this report. They are not stored on
              the server after processing.
            </span>
          </label>
          <div className="mt-5 flex items-center gap-4">
            <Button onClick={generate} disabled={!consent || loading}>
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" /> Generating your
                  report…
                </>
              ) : (
                "Generate my full report"
              )}
            </Button>
            <span className="flex items-center gap-1.5 text-[11px] text-zinc-500">
              <ShieldCheck className="h-3.5 w-3.5" /> One-time transmission,
              nothing stored
            </span>
          </div>
          {error ? (
            <p className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs text-amber-300">
              {error}
            </p>
          ) : null}
        </>
      )}
    </GlassCard>
  );
}
