// GENERATED by scripts/derive-display-window.mts — do not edit by hand.
//
// COMPOSITE_CDF[p] is the composite score at the p-th percentile of the
// modelled population (n=200000, independent draws from the
// means and SDs in norms.ts). The engine inverts it to turn a composite
// into a percentile, which is then mapped linearly onto the 0-10 headline.
//
// Consequence, and the reason this file exists: the headline is a rarity,
// not an opinion. A 5.5 means "half the modelled population sits below
// this", and one point of difference means the same amount of difference
// everywhere on the scale.
//
// To switch to real data: sort the composites of real scans and replace
// this array with their percentiles at the same resolution. Nothing else
// changes.

export const COMPOSITE_CDF: readonly number[] = [
  26.105, 64.357, 69.183, 71.891, 73.301, 74.661, 75.679, 76.838, 77.790, 78.466,
  79.084, 79.813, 80.564, 81.069, 81.496, 81.896, 82.497, 82.832, 83.196, 83.560,
  83.897, 84.160, 84.410, 84.702, 84.985, 85.235, 85.504, 85.713, 85.963, 86.180,
  86.425, 86.603, 86.762, 86.955, 87.147, 87.300, 87.455, 87.613, 87.783, 87.932,
  88.078, 88.252, 88.396, 88.543, 88.673, 88.783, 88.937, 89.068, 89.208, 89.330,
  89.436, 89.557, 89.684, 89.824, 89.962, 90.090, 90.182, 90.281, 90.383, 90.470,
  90.575, 90.664, 90.783, 90.890, 90.973, 91.078, 91.173, 91.258, 91.353, 91.476,
  91.591, 91.693, 91.795, 91.878, 91.978, 92.058, 92.149, 92.228, 92.315, 92.423,
  92.509, 92.632, 92.748, 92.856, 92.957, 93.065, 93.189, 93.294, 93.447, 93.581,
  93.669, 93.843, 93.999, 94.188, 94.331, 94.562, 94.792, 95.041, 95.359, 95.945,
  98.182,
];

/** Percentile (0-100) of `composite` in the modelled population. */
export function percentileOfComposite(composite: number): number {
  const t = COMPOSITE_CDF;
  if (composite <= t[0]) return 0;
  if (composite >= t[t.length - 1]) return 100;
  let lo = 0;
  let hi = t.length - 1;
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1;
    if (t[mid] <= composite) lo = mid;
    else hi = mid;
  }
  const span = t[hi] - t[lo] || 1e-9;
  return lo + (composite - t[lo]) / span;
}
