// Percentile of the overall score.
//
// WHAT THIS IS: the share of a MODELLED population that scores lower. The
// model draws each facial dimension around its published anthropometric
// mean and SD (lib/analysis/norms.ts) with a one-factor correlation
// structure, and runs the real scoring pipeline over 200 000 such faces.
// See scripts/derive-display-window.mts.
//
// WHAT THIS IS NOT: an attractiveness ranking, and not a percentile against
// real users. The score measures conformity to published reference
// proportions — it has never been validated against attractiveness ratings.
//
// WHY THIS FILE NO LONGER HOLDS A TABLE
// -------------------------------------
// It used to carry its own 91-entry lookup, generated by a separate script
// from a separate copy of the population model. Two copies of the same
// model are free to drift apart, and they did — the table was built when
// the scorer still used hand-cut bands, so after the rewrite it described a
// scoring function that no longer existed.
//
// The headline IS the percentile now: the engine converts the composite to
// a population percentile through COMPOSITE_CDF, then stretches it linearly
// onto [outLow, outHigh]. The percentile is recovered by inverting that
// stretch exactly — no table, nothing to keep in sync.

import { DEFAULT_WEIGHTS } from "./analysis/weights";
import { TOLERANCE_SD } from "./analysis/modules";
import { percentileOfComposite } from "./analysis/composite-cdf";
import { percentileOfVisionScore } from "./vision/rubric";
import type { ScanMetrics } from "./store";

export type ScoreSource = NonNullable<ScanMetrics["scoreSource"]>;

/**
 * Share of the population scoring below `overall` (0–100).
 *
 * TWO SCALES, AND WHY THE SOURCE HAS TO BE PASSED IN
 * --------------------------------------------------
 * A 6.0 does not mean the same thing in both engines, so one conversion
 * cannot serve both.
 *
 *   "geometry" — the headline is `outHigh − perSd · meanAbsZ`. Inverting
 *     that mapping back to a composite and looking it up in COMPOSITE_CDF
 *     is what keeps the badge and the headline telling one story.
 *
 *   "vision" — the headline came from GPT-4.1 against the anchor table in
 *     lib/vision/rubric.ts, which IS a percentile table. Running it through
 *     the geometry inverse instead would report the rarity of a composite
 *     that was never computed.
 *
 * Defaults to geometry, so every existing call site keeps its behaviour.
 */
export function percentileFor(overall: number, source: ScoreSource = "geometry"): number {
  if (source === "vision") return Math.round(percentileOfVisionScore(overall));

  const { outHigh, perSd } = DEFAULT_WEIGHTS.display;
  const meanAbsZ = Math.max(0, (outHigh - overall) / perSd);
  const composite = 100 * Math.exp(-0.5 * (meanAbsZ / TOLERANCE_SD) ** 2);
  return Math.round(percentileOfComposite(composite));
}

/**
 * The "top N%" figure — but only when it actually means something.
 *
 * A previous version always rendered `100 - percentile`, so a below-average
 * result proudly announced "Top 100%", which is both meaningless and reads
 * as praise. Returns null unless the result is genuinely in the upper half,
 * and the UI falls back to the plain percentile.
 */
export function topPercentFor(
  overall: number,
  source: ScoreSource = "geometry",
): number | null {
  const p = percentileFor(overall, source);
  if (p < 55) return null;
  return Math.max(1, 100 - p);
}
