// Percentile of the overall score.
//
// WHAT THIS IS: the share of a MODELLED population that scores lower. The
// model draws each facial dimension around its published anthropometric
// mean (Farkas) with a realistic coefficient of variation and runs the real
// scoring pipeline over 60 000 such faces. See scripts/build-percentiles.mts.
//
// WHAT THIS IS NOT: an attractiveness ranking, and not a percentile against
// real users. The score measures conformity to published reference
// proportions — it has never been validated against attractiveness ratings,
// and no real scan data feeds this table yet.
//
// TO SWITCH TO REAL DATA: collect the overall scores of real scans, sort
// them, and replace PERCENTILE_TABLE with the empirical CDF at the same
// 0.1-step resolution. `percentileFor` needs no changes. Only once that is
// done does this become a statement about actual users — and even then it
// describes proportion conformity, not attractiveness.

// generated by scripts/build-percentiles.mts — n=60000
export const PERCENTILE_TABLE: number[] = [
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2,
  0.3, 0.5, 0.5, 0.8, 1.2, 1.2, 1.7, 1.7, 2.6, 3.7,
  5.2, 5.2, 7.2, 7.2, 10.0, 13.6, 13.6, 18.2, 23.9, 30.7,
  30.7, 39.0, 39.0, 48.2, 57.9, 67.8, 67.8, 77.0, 77.0, 85.5,
  91.7, 91.7, 96.1, 98.6, 99.6, 99.6, 99.9, 100.0, 100.0, 100.0,
  100.0,
];

/** Share of the modelled population scoring below `overall` (0–100). */
export function percentileFor(overall: number): number {
  const idx = Math.round(overall * 10) - 10; // table starts at 1.0
  const v = PERCENTILE_TABLE[Math.max(0, Math.min(PERCENTILE_TABLE.length - 1, idx))];
  return Math.round(v);
}

/** The complementary "top N%" figure, floored at 1 so it never reads 0%. */
export function topPercentFor(overall: number): number {
  return Math.max(1, Math.round(100 - percentileFor(overall)));
}
