// Percentile of the overall score.
//
// WHAT THIS IS: the share of a MODELLED population that scores lower. The
// model draws each facial dimension around its published anthropometric
// mean and SD (lib/analysis/norms.ts) with a one-factor correlation
// structure, and runs the real scoring pipeline over 200 000 such faces.
// See scripts/derive-display-window.mts.
//
// WHAT THIS IS NOT: an attractiveness ranking, and not a percentile against
// real users. The score measures conformity to published reference
// proportions — it has never been validated against attractiveness ratings.
//
// WHY THIS FILE NO LONGER HOLDS A TABLE
// -------------------------------------
// It used to carry its own 91-entry lookup, generated by a separate script
// from a separate copy of the population model. Two copies of the same
// model are free to drift apart, and they did — the table was built when
// the scorer still used hand-cut bands, so after the rewrite it described a
// scoring function that no longer existed.
//
// The headline IS the percentile now: the engine converts the composite to
// a population percentile through COMPOSITE_CDF, then stretches it linearly
// onto [outLow, outHigh]. The percentile is recovered by inverting that
// stretch exactly — no table, nothing to keep in sync.

import { DEFAULT_WEIGHTS } from "./analysis/weights";

/** Share of the modelled population scoring below `overall` (0–100). */
export function percentileFor(overall: number): number {
  const { outLow, outHigh } = DEFAULT_WEIGHTS.display;
  const p = ((overall - outLow) / (outHigh - outLow)) * 100;
  return Math.round(Math.max(0, Math.min(100, p)));
}

/**
 * The "top N%" figure — but only when it actually means something.
 *
 * A previous version always rendered `100 - percentile`, so a below-average
 * result proudly announced "Top 100%", which is both meaningless and reads
 * as praise. Returns null unless the result is genuinely in the upper half,
 * and the UI falls back to the plain percentile.
 */
export function topPercentFor(overall: number): number | null {
  const p = percentileFor(overall);
  if (p < 55) return null;
  return Math.max(1, 100 - p);
}
