// Emits the percentile lookup table used by lib/percentile.ts.
//
// Runs the REAL scoring pipeline over a modelled population of faces (each
// dimension drawn around the Farkas anthropometric mean with a realistic
// spread) and reports, for each 0.1 step of the 0-10 score, what share of
// that population scores lower.
//
// Run:  npx tsx scripts/build-percentiles.mts

import { measure, P, type Point } from "../lib/measure";

const MM = {
  bizygomatic: 137, bigonial: 106, trichionMenton: 187,
  eyeFissureWidth: 31, intercanthal: 33, eyeFissureHeight: 10.5,
  browToLid: 20, noseWidth: 34, mouthWidth: 51,
  philtrum: 16, upperVermillion: 8, lowerVermillion: 10,
};
const SCALE = 0.52 / MM.bizygomatic;
const mm = (v: number) => v * SCALE;

// Box-Muller: anthropometric dimensions are roughly normal.
function gauss() {
  const u = Math.random() || 1e-9;
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * Math.random());
}
/** Draw around a mean with a coefficient of variation. */
const draw = (mean: number, cv: number) => mean * (1 + gauss() * cv);

function buildFace(f: Record<string, number>): Point[] {
  const pts: Point[] = Array.from({ length: 478 }, () => ({ x: 0.5, y: 0.5 }));
  const set = (i: number, x: number, y: number) => (pts[i] = { x, y });
  const C = 0.5;
  const top = 0.1;
  const third = f.faceHeight / 3;

  const yGlabella = top + mm(third + f.thirdSkew);
  const ySubnasale = top + mm(2 * third);
  const yMenton = top + mm(f.faceHeight);
  const yPupil = top + mm(f.faceHeight / 2);
  const yLipTop = ySubnasale + mm(f.philtrum);
  const yStomion = yLipTop + mm(f.upperVermillion);
  const yLidUpper = yPupil - mm(f.eyeFissureHeight / 2);

  set(P.forehead, C, top);
  set(P.glabella, C, yGlabella);
  set(P.subnasale, C, ySubnasale);
  set(P.menton, C + mm(f.asym), yMenton);
  set(P.nasion, C, yGlabella + mm(8));
  set(P.noseTip, C, ySubnasale - mm(15));
  set(P.zygoR, C - mm(f.bizygomatic / 2), yPupil + mm(18));
  set(P.zygoL, C + mm(f.bizygomatic / 2) + mm(f.asym), yPupil + mm(18));
  set(P.jawR, C - mm(f.bigonial / 2), yMenton - mm(45));
  set(P.jawL, C + mm(f.bigonial / 2) + mm(f.asym), yMenton - mm(45));

  const xInner = mm(f.intercanthal / 2);
  const xOuter = xInner + mm(f.eyeFissureWidth);
  const rise = Math.tan((f.tiltDeg * Math.PI) / 180) * mm(f.eyeFissureWidth);
  set(P.eyeInnerR, C - xInner, yPupil);
  set(P.eyeInnerL, C + xInner, yPupil);
  set(P.eyeOuterR, C - xOuter, yPupil - rise);
  set(P.eyeOuterL, C + xOuter, yPupil - rise);

  const xPupil = (xInner + xOuter) / 2;
  set(P.irisR, C - xPupil, yPupil - rise / 2);
  set(P.irisL, C + xPupil, yPupil - rise / 2);
  set(P.lidUpperR, C - xPupil, yLidUpper);
  set(P.lidLowerR, C - xPupil, yPupil + mm(f.eyeFissureHeight / 2));
  set(P.lidUpperL, C + xPupil, yLidUpper);
  set(P.lidLowerL, C + xPupil, yPupil + mm(f.eyeFissureHeight / 2));
  set(P.browR, C - xPupil, yLidUpper - mm(f.browToLid));
  set(P.browL, C + xPupil, yLidUpper - mm(f.browToLid));
  set(P.alarR, C - mm(f.noseWidth / 2), ySubnasale - mm(4));
  set(P.alarL, C + mm(f.noseWidth / 2), ySubnasale - mm(4));
  set(P.mouthR, C - mm(f.mouthWidth / 2), yStomion);
  set(P.mouthL, C + mm(f.mouthWidth / 2), yStomion);
  set(P.lipTop, C, yLipTop);
  set(P.lipUpperInner, C, yStomion);
  set(P.lipLowerInner, C, yStomion + mm(1));
  set(P.lipBottom, C, yStomion + mm(f.lowerVermillion));
  return pts;
}

const N = 60000;
const scores: number[] = [];
for (let i = 0; i < N; i++) {
  scores.push(
    measure(
      buildFace({
        // Coefficients of variation roughly doubled from the first pass.
        // The tight version produced scores only in 7.4-8.9, so the lookup
        // table was all zeros below that and the UI reported a meaningless
        // "top 100%" for anyone under the model's floor.
        bizygomatic: draw(MM.bizygomatic, 0.09),
        bigonial: draw(MM.bigonial, 0.13),
        faceHeight: draw(MM.trichionMenton, 0.09),
        eyeFissureWidth: draw(MM.eyeFissureWidth, 0.13),
        intercanthal: draw(MM.intercanthal, 0.16),
        eyeFissureHeight: draw(MM.eyeFissureHeight, 0.24),
        browToLid: draw(MM.browToLid, 0.32),
        noseWidth: draw(MM.noseWidth, 0.16),
        mouthWidth: draw(MM.mouthWidth, 0.14),
        philtrum: draw(MM.philtrum, 0.26),
        upperVermillion: draw(MM.upperVermillion, 0.34),
        lowerVermillion: draw(MM.lowerVermillion, 0.34),
        tiltDeg: 4.5 + gauss() * 5,
        thirdSkew: gauss() * 11,
        asym: gauss() * 4,
      }),
    ).overall,
  );
}
scores.sort((a, b) => a - b);

// For each 0.1 step, the share of the modelled population scoring lower.
const table: number[] = [];
for (let s = 10; s <= 100; s++) {
  const v = s / 10;
  let lo = 0;
  let hi = scores.length;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (scores[mid] < v) lo = mid + 1;
    else hi = mid;
  }
  table.push(Math.round((lo / scores.length) * 1000) / 10);
}

console.log(`// generated by scripts/build-percentiles.mts — n=${N}`);
console.log("export const PERCENTILE_TABLE: number[] = [");
for (let i = 0; i < table.length; i += 10) {
  console.log("  " + table.slice(i, i + 10).map((v) => v.toFixed(1)).join(", ") + ",");
}
console.log("];");
console.log(
  `// median ${scores[Math.floor(N / 2)]}  p10 ${scores[Math.floor(N * 0.1)]}  p90 ${scores[Math.floor(N * 0.9)]}`,
);
