// Generates lib/analysis/composite-cdf.ts — the composite → percentile map.
//
// WHY A CDF AND NOT A WINDOW
// --------------------------
// The display mapping used to be a straight line: composite 70→3.0,
// 98→9.5. Two things were wrong with it. The endpoints were chosen by
// hand, and the mapping was linear over a distribution that is not.
//
// The composite is a mean of Gaussian kernels, so it saturates near 100 and
// has a long left tail: p2 = 76, median = 87, p98 = 93. Mapping that
// linearly puts the median at 6.7 and squeezes the top three points of the
// scale into six composite points, while the bottom half of the scale is
// reached only by faces whose landmarks failed.
//
// Mapping through the CDF instead makes the headline a PERCENTILE of the
// modelled population. The median face scores mid-scale by construction,
// equal steps mean equal rarity, and nothing is chosen by hand.
//
//   npx tsx scripts/derive-display-window.mts
//
// CORRELATION MATTERS MORE THAN IT LOOKS
// --------------------------------------
// The first version of this script drew every measurement independently.
// That is wrong in a way that does real damage: averaging 22 independent
// draws produces a composite with far less variance than the truth, the
// CDF becomes very steep around the median, and a 0.7-point wobble in the
// composite then swings the headline by 0.7 points. The stability test
// caught it — pose drift was zero but landmark noise still moved the score.
//
// Facial dimensions are correlated: a wide face tends to have a wide jaw
// and a wide nose. Reported inter-correlations among facial measurements
// sit around r = 0.3-0.5 (Farkas' own tables, and the craniofacial factor
// analyses that follow from them). This uses a one-factor model at r = 0.4:
//
//     value = mean + sd · (λ·F + √(1−λ²)·ε),   λ = √0.4
//
// with F drawn once per face and ε per measurement. One shared factor is
// the simplest structure that reproduces a plausible correlation, and it is
// stated here rather than hidden because it visibly widens the distribution.
//
// LIMITATION: r = 0.4 uniform is still a model. Real correlations differ
// per pair and some are negative. Replacing this whole file with the
// empirical CDF of real scans is a drop-in change: same shape, measured
// numbers.

import { writeFileSync } from "node:fs";
import { NORMS, MEASUREMENT_IDS, type MeasurementId } from "../lib/analysis/norms";
import { evaluateGeometryModules, MODULE_IDS } from "../lib/analysis/modules";
import { DEFAULT_WEIGHTS } from "../lib/analysis/weights";

const N = 200_000;

// Fixed seed, so the generated table is reproducible.
let seed = 20260805;
const rnd = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);
function gauss() {
  const u = rnd() || 1e-9;
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * rnd());
}

const w = DEFAULT_WEIGHTS;
const composites: number[] = [];

/** Shared-factor loading giving r = 0.4 between any two measurements. */
const LAMBDA = Math.sqrt(0.4);
const RESIDUAL = Math.sqrt(1 - 0.4);

for (let i = 0; i < N; i++) {
  const values = {} as Record<MeasurementId, number>;
  // One latent factor per face — general facial size/shape.
  const factor = gauss();
  for (const id of MEASUREMENT_IDS) {
    const n = NORMS[id];
    const z = LAMBDA * factor + RESIDUAL * gauss();
    // Deviation measures are bounded at zero and right-skewed, so a folded
    // normal is the correct draw for them rather than a plain one.
    values[id] =
      n.oneSided === "lower"
        ? Math.abs(z) * n.sd + Math.max(0, n.mean - n.sd)
        : n.mean + z * n.sd;
  }

  const modules = evaluateGeometryModules(values, [], w.modules);
  let num = 0;
  let den = 0;
  for (const id of MODULE_IDS) {
    const m = modules[id];
    if (!m || m.score === null) continue;
    const eff = m.weight * m.confidence;
    num += eff * m.score;
    den += eff;
  }
  if (den > 0) composites.push(num / den);
}

composites.sort((a, b) => a - b);
const at = (p: number) => composites[Math.floor((p / 100) * (composites.length - 1))];

// 101 breakpoints: the composite value at each whole percentile.
const table = Array.from({ length: 101 }, (_, p) => Number(at(p).toFixed(3)));

const rows: string[] = [];
for (let i = 0; i < table.length; i += 10) {
  rows.push("  " + table.slice(i, i + 10).map((v) => v.toFixed(3)).join(", ") + ",");
}

const file = `// GENERATED by scripts/derive-display-window.mts — do not edit by hand.
//
// COMPOSITE_CDF[p] is the composite score at the p-th percentile of the
// modelled population (n=${composites.length}, independent draws from the
// means and SDs in norms.ts). The engine inverts it to turn a composite
// into a percentile, which is then mapped linearly onto the 0-10 headline.
//
// Consequence, and the reason this file exists: the headline is a rarity,
// not an opinion. A 5.5 means "half the modelled population sits below
// this", and one point of difference means the same amount of difference
// everywhere on the scale.
//
// To switch to real data: sort the composites of real scans and replace
// this array with their percentiles at the same resolution. Nothing else
// changes.

export const COMPOSITE_CDF: readonly number[] = [
${rows.join("\n")}
];

/** Percentile (0-100) of \`composite\` in the modelled population. */
export function percentileOfComposite(composite: number): number {
  const t = COMPOSITE_CDF;
  if (composite <= t[0]) return 0;
  if (composite >= t[t.length - 1]) return 100;
  let lo = 0;
  let hi = t.length - 1;
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1;
    if (t[mid] <= composite) lo = mid;
    else hi = mid;
  }
  const span = t[hi] - t[lo] || 1e-9;
  return lo + (composite - t[lo]) / span;
}
`;

writeFileSync(new URL("../lib/analysis/composite-cdf.ts", import.meta.url), file);

console.log(`n = ${composites.length}`);
console.log(
  `composite:  p2 ${at(2).toFixed(1)}  p25 ${at(25).toFixed(1)}  ` +
    `median ${at(50).toFixed(1)}  p75 ${at(75).toFixed(1)}  p98 ${at(98).toFixed(1)}`,
);
const { outLow, outHigh } = w.display;
const score = (p: number) => outLow + (p / 100) * (outHigh - outLow);
console.log("\nHeadline nach Perzentil-Mapping:");
for (const p of [1, 5, 10, 25, 50, 75, 90, 95, 99]) {
  console.log(`  p${String(p).padStart(2)}  →  ${score(p).toFixed(1)}`);
}
console.log("\ngeschrieben: lib/analysis/composite-cdf.ts");
